// AUTOGENERATED by FrameLoop.jl (Wed Sep 18 17:56:41 NZST 2024)
// Do not edit this file directly if you value your sanity...

// frame size
#define WIDTH 1024
#define HEIGHT 1024

// masking
#define MASK_BOARD_CUT_IN 150
#define MASK_COMP_CUT_IN 255
#define MASK_BOARD_CUT_OUT 150
#define MASK_COMP_CUT_OUT 255

// centroids algorithm
#define MAX_SEARCH_BUF 5000
#define MAX_NUM_CENTROIDS 200
#define GRID_STEP 16

// ENDS